#!/bin/bash

usage() {
    cat <<END
usage: $0 <opt>
<opt>: -a: copy all files
       -b: copy bash files
       -n: link nvim files
       -c: link .config/files
       -f: copy fonts
END
    exit 1
}

while getopts :abncf opt; do
    case $opt in
        a) a=1;;
        b) b=1;;
        n) n=1;;
        c) c=1;;
        f) f=1;;
        *) usage
    esac
done

if [[ -z $1 ]]; then usage; fi

if [[ -n $a ]] || [[ -n $b ]]; then
    (set -x
    cp .dircolors ~/
    cp .inputrc ~/
    cp .bashrc ~/
    cp .bash_aliases ~/
    cp .clang-format ~/
    cp .sher.sh ~/)
fi

if [[ -n $a ]] || [[ -n $n ]]; then
    mkdir -p ~/.config
    (set -x
    ln -sf `pwd`/.config/nvim ~/.config)
fi

if [[ -n $a ]] || [[ -n $c ]]; then
    mkdir -p ~/.config
    for config in `ls .config`; do
        config="`pwd`/.config/$config"
        (set -x
        ln -sf "$config" ~/.config)
    done
fi

if [[ -n $a ]] || [[ -n $f ]]; then
    mkdir -p ~/.local/share/fonts
    cp -v ./fonts/* ~/.local/share/fonts
fi
