#!/bin/bash

usage() {
    cat <<END
usage: $0 <opt>
<opt>: -a: copy all files
       -b: copy bash files
       -n: copy nvim files
END
    exit 1
}

while getopts :abvnz opt; do
    case $opt in
        a) a=1;;
        b) b=1;;
        n) n=1;;
        *) usage
    esac
done

if [[ -z $1 ]]; then usage; fi

if [[ -n $a ]] || [[ -n $b ]]; then
    (set -x
    cp .dircolors ~/
    cp .inputrc ~/
    cp .bashrc ~/
    cp .bash_aliases ~/
    cp .clang-format ~/
    cp .sher.sh ~/)
fi

if [[ -n $a ]] || [[ -n $n ]]; then
    mkdir -p ~/.config
    (set -x
    ln -sf `pwd`/nvim ~/.config)
fi
